sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

python:
  - "3.4"

before_install:
  - sudo pip install cpp-coveralls
  - sudo apt-get install python3-requests

install:
  - cd AppServer
  - chmod +x install.sh
  - sudo ./install.sh

script:
- cd src/tests
- python restTester.py test

notifications:
  slack: 7552-tallerii:zleHiBV470j46D1j36Xl0TUb
