sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - sudo python3 -m easy_install pip
  - sudo pip3 install requests

install:
  - cd AppServer
  - chmod +x install.sh
  - sudo ./install.sh

script:
- cd src/tests
- pip -V
- python -V
- python restTester.py test

notifications:
  slack: 7552-tallerii:zleHiBV470j46D1j36Xl0TUb
