sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls

install:
  - cd AppServer
  - chmod +x install.sh
  - sudo ./install.sh

notifications:
  slack: 7552-tallerii:zleHiBV470j46D1j36Xl0TUb
