sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo pip install cpp-coveralls
#  - sudo pip-2.7 install requests

install:
  - cd AppServer
  - chmod +x install.sh
  - sudo ./install.sh

script:
#- cd src/tests
#- pip -V
#- python -V
#- python restTester.py test

notifications:
  slack: 7552-tallerii:zleHiBV470j46D1j36Xl0TUb
