language: cpp

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - git clone --branch=master https://github.com/open-source-parsers/jsoncpp.git

install:
 - sudo apt-get install -qq g++-4.8
 - export CXX="g++-4.8"
 - cd jsoncpp
 - python amalgamate.py
 - mkdir build && cd build
 - cmake .. -DCMAKE_INSTALL_PREFIX="json" -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON -DJSONCPP_WITH_CMAKE_PACKAGE=ON -DCMAKE_BUILD_TYPE="Release"
 - make -j2 install
 - apt-get install libcurl4-openssl-dev
after_failure:
- cat build/reports/*/*.xml
